# Generated by Django 6.0.4 on 2026-07-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('session_started', 'session_started'), ('document_opened', 'document_opened'), ('document_closed', 'document_closed'), ('search_performed', 'search_performed'), ('search_param_changed', 'search_param_changed'), ('result_navigated', 'result_navigated'), ('scope_changed', 'scope_changed'), ('mode_changed', 'mode_changed'), ('iiif_toggled', 'iiif_toggled'), ('font_size_changed', 'font_size_changed'), ('feedback_submitted', 'feedback_submitted')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('client_ts', models.DateTimeField()),
                ('server_ts', models.DateTimeField(auto_now_add=True)),
                ('app_version', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['-server_ts'],
            },
        ),
    ]
