# Generated by Django 6.0.4 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_questionnaireresponse_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(choices=[('backend_5xx', 'backend_5xx')], max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=255)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('server_ts', models.DateTimeField(auto_now_add=True)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-server_ts'],
            },
        ),
    ]
