# Generated by Django 6.0.4 on 2026-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_errorreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorevent',
            name='event_type',
            field=models.CharField(choices=[('session_started', 'session_started'), ('document_opened', 'document_opened'), ('document_closed', 'document_closed'), ('search_performed', 'search_performed'), ('search_param_changed', 'search_param_changed'), ('result_navigated', 'result_navigated'), ('scope_changed', 'scope_changed'), ('mode_changed', 'mode_changed'), ('iiif_toggled', 'iiif_toggled'), ('font_size_changed', 'font_size_changed'), ('tag_entity_selected', 'tag_entity_selected'), ('feedback_submitted', 'feedback_submitted')], max_length=32),
        ),
    ]
