/*
resize panel part is generated by copilot.
*/

import React, { useState } from 'react';
import './App.css';

function App() {
  // file management
  const [documentCount, setDocumentCount] = useState(2);
  const [documents, setDocuments] = useState([
    { id: 1, file: null, content: '' },
    { id: 2, file: null, content: '' }
  ]);

  // parameters
  const [windowSize, setWindowSize] = useState(1.0);
  const [stepSize, setStepSize] = useState(1);
  const [dissimilarityThreshold, setDissimilarityThreshold] = useState(0.5);
  const [topK, setTopK] = useState(1);

  // use object to store the selected text
  const [selectedTexts, setSelectedTexts] = useState({});

  // search results
  const [searchResults, setSearchResults] = useState([]);
  
  // manual search input
  const [manualSearchText, setManualSearchText] = useState('');

  // highlight status
  const [highlight, setHighlight] = useState(null);

  // filter status
  const [filteredDocId, setFilteredDocId] = useState(null);


  // sidebar collapsed status
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);

  // current search query (only updated when search is pressed)
  const [currentSearchQuery, setCurrentSearchQuery] = useState(null);
  const [currentSearchSourceDoc, setCurrentSearchSourceDoc] = useState(null);

  // help tooltip status
  const [activeTooltip, setActiveTooltip] = useState(null);

  // preset mode tooltip status
  const [activePresetTooltip, setActivePresetTooltip] = useState(null);

  // algorithm selection status (0: Standard, 1: Irish)
  const [selectedAlgorithm, setSelectedAlgorithm] = useState(0);

  // reupload confirmation popup status
  const [reuploadConfirm, setReuploadConfirm] = useState({ show: false, docId: null, fileName: '' });

  // document font size status (default 14px)
  const [documentFontSizes, setDocumentFontSizes] = useState({});

  // record the last selected result for each document
  const [lastSelectedResults, setLastSelectedResults] = useState({});

  // container height status
  const [contentHeight, setContentHeight] = useState(500);
  const [overviewHeight, setOverviewHeight] = useState(150);
  const [isDragging, setIsDragging] = useState(false);
  const [userAdjustedRatio, setUserAdjustedRatio] = useState(null);



  // toggle sidebar collapsed status
  const toggleSidebar = () => {
    setIsSidebarCollapsed(!isSidebarCollapsed);
  };


  // preset mode
  const presets = {
    fast: {
      name: "Quick Search",
      description: "fast but may miss some results.",
      windowSize: 2.0,
      stepSize: 6,
      dissimilarityThreshold: 0.8,
      topK: 5
    },
    standard: {
      name: "Standard search",
      description: "balanced",
      windowSize: 1.0,
      stepSize: 3,
      dissimilarityThreshold: 0.5,
      topK: 5
    },
    precise: {
      name: "Precise search",
      description: "Slow and may cotains similar or duplicate results",
      windowSize: 1.2,
      stepSize: 1,
      dissimilarityThreshold: 0.3,
      topK: 10
    }
  };

  // apply preset mode
  const applyPreset = (presetKey) => {
    const preset = presets[presetKey];
    setWindowSize(preset.windowSize);
    setStepSize(preset.stepSize);
    setDissimilarityThreshold(preset.dissimilarityThreshold);
    setTopK(preset.topK);
  };

  // clear search bar content
  const clearSearch = () => {
    setManualSearchText('');
  };

  // handle drag to adjust container height
  const handleMouseDown = (e) => {
    setIsDragging(true);
    e.preventDefault();
  };

  const handleMouseMove = (e) => {
    if (!isDragging) return;
    
    const containerElement = document.querySelector('.main-content');
    if (!containerElement) return;
    
    const rect = containerElement.getBoundingClientRect();
    const mouseY = e.clientY;
    const relativeY = mouseY - rect.top;
    const containerHeight = rect.height;
    
    // minimum height (pixel value)
    const minContentHeightPx = 340;
    const minOverviewHeightPx = 150;
    const resizeHandleHeight = 4; // height of resize handle
    
    // ensure there is enough space for two containers and resize handle
    const availableHeight = containerHeight - resizeHandleHeight;
    if (availableHeight < minContentHeightPx + minOverviewHeightPx) {
      return; // if there is not enough space, do not adjust
    }
    
    // calculate new content height (pixel value)
    const requestedContentHeight = relativeY;
    const newContentHeight = Math.max(minContentHeightPx, Math.min(availableHeight - minOverviewHeightPx, requestedContentHeight));
    const newOverviewHeight = availableHeight - newContentHeight;
    
    // save the user's adjusted ratio
    const newRatio = newContentHeight / availableHeight;
    setUserAdjustedRatio(newRatio);
    
    setContentHeight(newContentHeight);
    setOverviewHeight(newOverviewHeight);
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  // initialize container height
  const initializeContainerHeights = React.useCallback(() => {
    const containerElement = document.querySelector('.main-content');
    if (!containerElement) return;
    
    const containerHeight = containerElement.getBoundingClientRect().height;
    const minContentHeightPx = 340;
    const minOverviewHeightPx = 150;
    const resizeHandleHeight = 4;
    
    const availableHeight = containerHeight - resizeHandleHeight;
    
    if (availableHeight >= minContentHeightPx + minOverviewHeightPx) {
      // if the user has adjusted the ratio, use the user's ratio; otherwise, content is maximized, and overview is minimized
      let contentRatio;
      if (userAdjustedRatio !== null) {
        contentRatio = userAdjustedRatio;
      } else {
        // default: overview is set to the minimum height, and content occupies the remaining space
        const defaultOverviewHeight = minOverviewHeightPx;
        const defaultContentHeight = availableHeight - defaultOverviewHeight;
        contentRatio = defaultContentHeight / availableHeight;
      }
      const requestedContentHeight = availableHeight * contentRatio;
      const newContentHeight = Math.max(minContentHeightPx, Math.min(availableHeight - minOverviewHeightPx, requestedContentHeight));
      const newOverviewHeight = availableHeight - newContentHeight;
      
      setContentHeight(newContentHeight);
      setOverviewHeight(newOverviewHeight);
    }
  }, [userAdjustedRatio]);

  // initialize height when the component is mounted
  React.useEffect(() => {
    const timer = setTimeout(initializeContainerHeights, 100); // slightly delay to ensure DOM rendering is complete
    return () => clearTimeout(timer);
  }, [initializeContainerHeights]);

    // listen to window size change
  React.useEffect(() => {
    const handleResize = () => {
      // delay execution to ensure DOM update is complete
      setTimeout(initializeContainerHeights, 50);
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, [initializeContainerHeights]);

  // add global event listener
  React.useEffect(() => {
    if (isDragging) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = 'ns-resize';
      document.body.style.userSelect = 'none';
      
      return () => {
        document.removeEventListener('mousemove', handleMouseMove);
        document.removeEventListener('mouseup', handleMouseUp);
        document.body.style.cursor = '';
        document.body.style.userSelect = '';
      };
    }
  }, [isDragging]);

  // add global event listener

  // filter search results
  const handleCardClick = (docId) => {
    if (filteredDocId === docId) {
      // if the clicked document is the current filtered document, cancel the filter
      setFilteredDocId(null);
    } else {
      // set the new filtered document
      setFilteredDocId(docId);
    }
  };

  // get filtered search results
  const getFilteredResults = () => {
    if (filteredDocId === null) {
      return searchResults;
    }
    return searchResults.filter(result => result.docId === filteredDocId);
  };


  // get the minimum available ID (1-5 range)
  const getAvailableId = () => {
    const usedIds = documents.map(doc => doc.id);
    for (let i = 1; i <= 5; i++) {
      if (!usedIds.includes(i)) {
        return i;
      }
    }
    return null; // if no id is available
  };

  // fill empty documents first, and only create new documents after the user selects a file
  const addDocument = () => {
    // find the first empty document
    const emptyDoc = documents.find(doc => !doc.content);
    
    if (emptyDoc) {
      // if there is an empty document, trigger its file selection
      const fileInput = document.getElementById(`file${emptyDoc.id}-upload`);
      if (fileInput) {
        fileInput.click();
      }
    } else {
      // if all documents have content and the limit is not reached, create a temporary file input to select a file
      if (documentCount >= 5) return;
      
      // create a temporary file input
      const tempInput = document.createElement('input');
      tempInput.type = 'file';
      tempInput.accept = '.txt';
      tempInput.style.display = 'none';
      
      tempInput.onchange = (e) => {
        const file = e.target.files[0];
        if (file) {
          // use the minimum available ID (instead of the maximum ID+1)
          const newId = getAvailableId();
          if (newId === null) return; // if no id is available
          
          const reader = new FileReader();
          reader.onload = (event) => {
            setDocuments([...documents, { 
              id: newId, 
              file: file, 
              content: event.target.result 
            }]);
            setDocumentCount(documentCount + 1);
          };
          reader.onerror = () => {
            alert('Error reading file.');
          };
          reader.readAsText(file);
        }
        // clear the temporary input element
        document.body.removeChild(tempInput);
      };
      
      // add to DOM and trigger click
      document.body.appendChild(tempInput);
      tempInput.click();
    }
  };

  // delete document
  const removeDocument = (docId) => {
    if (documentCount <= 2) return;
    setDocuments(documents.filter(doc => doc.id !== docId));
    setDocumentCount(documentCount - 1);
    // clear the selected text of the document
    const newSelectedTexts = { ...selectedTexts };
    delete newSelectedTexts[docId];
    setSelectedTexts(newSelectedTexts);
  };

  // reupload file confirmation
  const handleReupload = (docId) => {
    const doc = documents.find(d => d.id === docId);
    const fileName = doc?.file?.name || `Document ${docId}`;
    
    setReuploadConfirm({
      show: true,
      docId: docId,
      fileName: fileName
    });
  };

  // confirm reupload
  const confirmReupload = () => {
    document.getElementById(`file${reuploadConfirm.docId}-upload`).click();
    setReuploadConfirm({ show: false, docId: null, fileName: '' });
  };

  // cancel reupload
  const cancelReupload = () => {
    setReuploadConfirm({ show: false, docId: null, fileName: '' });
  };

  // get document font size
  const getDocumentFontSize = (docId) => {
    return documentFontSizes[docId] || 14; // default 14px
  };

  // get color class name based on score - low score uses brighter blue
  const getScoreColorClass = (score) => {
    if (score <= 0.2) return 'score-excellent'; // bright blue
    if (score <= 0.4) return 'score-good';      // medium blue
    if (score <= 0.6) return 'score-fair';      // light blue
    return 'score-poor';                        // light gray
  };

  // adjust font size
  const adjustFontSize = (docId, increment) => {
    const currentSize = getDocumentFontSize(docId);
    const newSize = currentSize + increment;
    if (newSize >= 10 && newSize <= 18) {
      setDocumentFontSizes({
        ...documentFontSizes,
        [docId]: newSize
      });
    }
  };

  // file upload and display content directly
  const handleFileChange = (event, docId) => {
    const file = event.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (e) => {
      setDocuments(documents.map(doc => 
        doc.id === docId 
          ? { ...doc, file: file, content: e.target.result }
          : doc
      ));
    };
    reader.onerror = () => {
      alert('Error reading file.');
    };
    reader.readAsText(file);
  };

  // parameter slider
  const handleParamChange = (event, param) => {
    const value = parseFloat(event.target.value);
    switch(param) {
      case 'window': setWindowSize(value); break;
      case 'step': setStepSize(value); break;
      case 'threshold': setDissimilarityThreshold(value); break;
      case 'topK': setTopK(value); break;
      default: break;
    }
  };

  // select text
const handleTextSelection = (docId) => {
    const selection = window.getSelection();
    const text = selection.toString().trim();
    console.log(text)
    if (text) {
      setSelectedTexts({
        ...selectedTexts,
        [docId]: {
          text: text,
          source: docId
        }
      });
    } else {
      // clear the selection 
      const updatedSelections = { ...selectedTexts };
      delete updatedSelections[docId];
      setSelectedTexts(updatedSelections);
    }
  };

  // manual search handler - search all documents
  const handleManualSearch = () => {
    if (!manualSearchText.trim()) return;
    const documentsWithContent = documents.filter(doc => doc.content);
    if (documentsWithContent.length === 0) return;
    
    performSearch(manualSearchText, documentsWithContent, 'manual', null);
  };

  // search logic - search from one document to all other documents
  const handleSearch = (sourceDocId) => {
    const selectionInfo = selectedTexts[sourceDocId];
    if (!selectionInfo || !selectionInfo.text) return;
    
    const searchText = selectionInfo.text;
    const targetDocs = documents.filter(doc => doc.id !== sourceDocId && doc.content);
    if (targetDocs.length === 0) return;
    
    performSearch(searchText, targetDocs, 'cross-doc', sourceDocId);
  };

  // perform search
  const performSearch = (searchText, targetDocs, searchType, sourceDocId) => {
    // clear the selected text of other documents (only when searching cross-doc)
    if (searchType === 'cross-doc') {
      const newSelectedTexts = { ...selectedTexts };
      Object.keys(newSelectedTexts).forEach(docId => {
        if (parseInt(docId) !== sourceDocId) {
          delete newSelectedTexts[docId];
        }
      });
      setSelectedTexts(newSelectedTexts);
    }
    
    // search all target documents
    const searchPromises = targetDocs.map(doc => 
      fetch('/api/search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          searchText,
          article: doc.content,
          windowSize,
          stepSize,
          dissimilarityThreshold,
          topK,
          irish_algo: selectedAlgorithm
        }),
      }).then(response => {
        if (!response.ok) {
          return response.json().then(errorData => {
            throw new Error(errorData.error || 'Search failed');
          });
        }
        return response.json();
      }).then(data => ({
        results: data.results || [],
        docId: doc.id
      }))
    );
    
    Promise.all(searchPromises)
      .then(searchResults => {
        // merge results
        const combinedResults = [];
        searchResults.forEach(({ results, docId }) => {
          results.forEach(result => {
            combinedResults.push({
              ...result,
              docId: docId
            });
          });
        });
        
        // sort by score
        combinedResults.sort((a, b) => a.score - b.score);
        
        setSearchResults(combinedResults);
        setLastSelectedResults({});
        
        // set search query information
        setCurrentSearchQuery(searchText);
        setCurrentSearchSourceDoc(searchType === 'manual' ? null : sourceDocId);
        
        // if there is a result, automatically select the first one
        if (combinedResults.length > 0) {
          setTimeout(() => {
            handleResultClick(combinedResults[0], 0);
          }, 0);
        }
      })
      .catch(error => {
        alert(error.message);
      });
  };

  // handle click to highlight search result
  const handleResultClick = (result, idx) => {
    setHighlight({
      text: result.text,
      index: idx,
      docId: result.docId
    });

    // record the last selected result of this document
    if (result.docId) {
      setLastSelectedResults({
        ...lastSelectedResults,
        [result.docId]: result
      });
      setFilteredDocId(result.docId);
    }
  };

  // render content with highlighted text 
  function renderContentWithHighlight(content, highlightInfo, className = 'highlighted') {
    if (!highlightInfo) return content;
    
    // if it is a string (backward compatibility)
    if (typeof highlightInfo === 'string') {
      const idx = content.indexOf(highlightInfo);
      if (idx === -1) return content;
      return (
        <>
          {content.substring(0, idx)}
          <span className={className}>{highlightInfo}</span>
          {content.substring(idx + highlightInfo.length)}
        </>
      );
    }
    
    // if it is a selection information object
    if (highlightInfo.text && highlightInfo.textContent) {
      // find the matching text paragraph in the full content
      const targetText = highlightInfo.textContent;
      const selectedText = highlightInfo.text;
      const startInParagraph = highlightInfo.startOffset;
      
      // find the position of targetText in content
      let contentIdx = content.indexOf(targetText);
      if (contentIdx !== -1) {
        // calculate the actual position of the selected text in the full content
        const actualStart = contentIdx + startInParagraph;
        const actualEnd = actualStart + selectedText.length;
        
        return (
          <>
            {content.substring(0, actualStart)}
            <span className={className}>{content.substring(actualStart, actualEnd)}</span>
            {content.substring(actualEnd)}
          </>
        );
      }
    }
    
    return content;
  }

  return (
    <div className="app-flex">
      {/* left parameter area */}
      <div className={`sidebar ${isSidebarCollapsed ? 'sidebar-collapsed' : ''}`}>
        {/* application title */}
        <div className="app-title">
          <h2>Celtic Finder</h2>
        </div>
        
        <div className="sidebar-toggle">
          <button 
            className="sidebar-toggle-btn"
            onClick={toggleSidebar}
            title={isSidebarCollapsed ? "Expand sidebar" : "Collapse sidebar"}
          >
            {isSidebarCollapsed ? '»' : '«'}
          </button>
        </div>
        {!isSidebarCollapsed && (
          <div className="sidebar-content">
            {/* preset mode selection */}
            <div className="preset-section">
              <h4 className="preset-title">Search Mode</h4>
              <div className="preset-buttons">
                {Object.entries(presets).map(([key, preset]) => (
                  <div key={key} className="preset-btn-container">
                    <button
                      className="preset-btn"
                      onClick={() => applyPreset(key)}
                      onMouseEnter={() => setActivePresetTooltip(key)}
                      onMouseLeave={() => setActivePresetTooltip(null)}
                    >
                      {preset.name}
                    </button>
                    {activePresetTooltip === key && (
                      <div className="preset-tooltip">
                        <div className="preset-tooltip-content">
                          {preset.description}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
            
          </div>
        )}

        {/* algorithm selection */}
        {!isSidebarCollapsed && (
          <div className="algorithm-section">
            <h4 className="algorithm-title">Algorithm</h4>
            <div className="algorithm-buttons">
              <button
                className={`algorithm-btn ${selectedAlgorithm === 0 ? 'active' : ''}`}
                onClick={() => setSelectedAlgorithm(0)}
              >
                Standard Algorithm
              </button>
              <button
                className={`algorithm-btn ${selectedAlgorithm === 1 ? 'active' : ''}`}
                onClick={() => setSelectedAlgorithm(1)}
              >
                Irish Algorithm
              </button>
            </div>
          </div>
        )}

        
        {/* parameter control */}
        {!isSidebarCollapsed && (
          <div className="parameters">
            <div className="parameter">
              <div className="parameter-label">
                <label>Match Length: {Math.round(windowSize * 100)}%</label>
                <div className="help-icon-container">
                  <span 
                    className="help-icon"
                    onMouseEnter={() => setActiveTooltip('windowSize')}
                    onMouseLeave={() => setActiveTooltip(null)}
                  >
                    ?
                  </span>
                  {activeTooltip === 'windowSize' && (
                    <div className="tooltip">
                      <div className="tooltip-title">Match Length</div>
                      <div className="tooltip-content">
                        This setting controls how long the result is compared to the text you selected. 
                        <br />
                        By default, it's set to 100%, so if you search with 50 words, 
                        you'll get a 50 words result.If you change it to 200%, 
                        the result will be twice as long, exactly 100 words.

                      </div>
                    </div>
                  )}
                </div>
              </div>
              <input type="range" min="0.1" max="3" step="0.01" value={windowSize} onChange={e => handleParamChange(e, 'window')} />
            </div>
            <div className="parameter">
              <div className="parameter-label">
                <label>Precision: {stepSize}</label>
                <div className="help-icon-container">
                  <span 
                    className="help-icon"
                    onMouseEnter={() => setActiveTooltip('stepSize')}
                    onMouseLeave={() => setActiveTooltip(null)}
                  >
                    ?
                  </span>
                  {activeTooltip === 'stepSize' && (
                    <div className="tooltip">
                      <div className="tooltip-title">Search Precision</div>
                      <div className="tooltip-content">
                            Lowering the precision makes the search more comprehensive but slower.
                            <br />
                            You may also see very similar or nearly duplicate results.
                            <br />
                            A higher setting makes the search faster, 
                            but you may miss some of the results you're looking for.
                      </div>
                    </div>
                  )}
                </div>
              </div>
              <input type="range" min="1" max="10" step="1" value={stepSize} onChange={e => handleParamChange(e, 'step')} />
            </div>
            <div className="parameter">
              <div className="parameter-label">
                <label>Dissimilarity Requirement: {dissimilarityThreshold}</label>
                <div className="help-icon-container">
                  <span 
                    className="help-icon"
                    onMouseEnter={() => setActiveTooltip('threshold')}
                    onMouseLeave={() => setActiveTooltip(null)}
                  >
                    ?
                  </span>
                  {activeTooltip === 'threshold' && (
                    <div className="tooltip">
                      <div className="tooltip-title">Dissimilarity Requirement</div>
                      <div className="tooltip-content">
                        • 0: identical
                        <br />
                        • 1: 100% different.
                        <br />
                        By setting it to 0.5, 
                        you are looking for results that are between 0% and 50% different from your original text."
                      </div>
                    </div>
                  )}
                </div>
              </div>
              <input type="range" min="0" max="1" step="0.01" value={dissimilarityThreshold} onChange={e => handleParamChange(e, 'threshold')} />
            </div>
            <div className="parameter">
              <div className="parameter-label">
                <label>Number of Results: {topK}</label>
                <div className="help-icon-container">
                  <span 
                    className="help-icon"
                    onMouseEnter={() => setActiveTooltip('topK')}
                    onMouseLeave={() => setActiveTooltip(null)}
                  >
                    ?
                  </span>
                  {activeTooltip === 'topK' && (
                    <div className="tooltip">
                      <div className="tooltip-title">Number of Results</div>
                      <div className="tooltip-content">
                        Number of search results to display from each document.
                      </div>
                    </div>
                  )}
                </div>
              </div>
              <input type="range" min="1" max="50" step="1" value={topK} onChange={e => handleParamChange(e, 'topK')} />
            </div>
          </div>
        )}

          {/* search results */}
        {searchResults.length > 0 && !isSidebarCollapsed && (
          <div className="sidebar-search-results">
            <div className="sidebar-results-header">
              <span className="results-title">Search Results</span>
              <span className="results-count">
                {getFilteredResults().length} result{getFilteredResults().length > 1 ? 's' : ''}
              </span>
            </div>
            
            {getFilteredResults().length === 0 ? (
              <div className="sidebar-no-results">
                No results found for: {currentSearchQuery || manualSearchText}
              </div>
            ) : (
              <div className="sidebar-results-content">
                {getFilteredResults().map((result, idx) => (
                  <div
                    key={idx}
                    className={`sidebar-result-item${highlight && highlight.index === searchResults.indexOf(result) ? ' result-selected' : ''}${result.docId ? ` doc-${result.docId}-bg` : ''}`}
                    onClick={() => handleResultClick(result, searchResults.indexOf(result))}
                  >
                    <div className="sidebar-result-text">{result.text}</div>
                    <div className={`sidebar-result-score ${getScoreColorClass(result.score)}`}>{result.score.toFixed(2)}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

      </div>

      {/* right content area */}
      <div className="main-content">
        {/* manual search bar */}
        <div className="manual-search-bar">
          <input
            type="text"
            placeholder="Enter search text. Your query will search through all uploaded sources"
            value={manualSearchText}
            onChange={(e) => setManualSearchText(e.target.value)}
            className="search-input-large"
            onKeyPress={(e) => e.key === 'Enter' && handleManualSearch()}
          />
          <div className="search-buttons-compact">
            <button 
              className="search-btn-compact" 
              onClick={handleManualSearch} 
              disabled={!manualSearchText.trim() || documents.filter(doc => doc.content).length === 0}
              title="Search in all documents"
            >
              Search
            </button>
            <button 
              className="clear-btn-compact" 
              onClick={clearSearch}
              disabled={!manualSearchText.trim()}
              title="Clear search input"
            >
              Clear
            </button>
          </div>
        </div>
        
        <div className="content-display-container" style={{ height: `${contentHeight}px` }}>
          <div className="content-display">
              {documents.map((doc) => (
            <div key={doc.id} className="file-content">
              {/* document title and action buttons */}
              <div className={`document-header doc-${doc.id}-header`}>
                {doc.file && <div className={`filename doc-${doc.id}-filename`}>{doc.file.name}</div>}
                {!doc.file && <div className={`filename doc-${doc.id}-filename`}>Source {doc.id}</div>}
                <div className="document-actions">
                  <button 
                    className="font-size-btn decrease-font-btn" 
                    onClick={() => adjustFontSize(doc.id, -1)}
                    title="Decrease font size"
                    disabled={getDocumentFontSize(doc.id) <= 10}
                  >
                    A-
                  </button>
                  <button 
                    className="font-size-btn increase-font-btn" 
                    onClick={() => adjustFontSize(doc.id, 1)}
                    title="Increase font size"
                    disabled={getDocumentFontSize(doc.id) >= 18}
                  >
                    A+
                  </button>
                  <button 
                    className="reupload-btn" 
                    onClick={() => handleReupload(doc.id)}
                    title="Reupload file"
                  >
                    ↻
                  </button>
                  <button 
                    className="remove-btn" 
                    onClick={() => removeDocument(doc.id)}
                    title="Remove document"
                    disabled={documentCount <= 2}
                  >
                    ×
                  </button>
                </div>
              </div>
              
              {/* document content */}
              <div
                className={`text-content${selectedTexts[doc.id] ? ' selected' : ''}`}
                onMouseUp={() => handleTextSelection(doc.id)}
                style={{ fontSize: `${getDocumentFontSize(doc.id)}px` }}
              >
                {highlight && highlight.docId === doc.id
                  ? renderContentWithHighlight(doc.content, highlight.text, 'highlighted')
                  : (selectedTexts[doc.id] ? renderContentWithHighlight(doc.content, selectedTexts[doc.id], 'selected-highlighted') : doc.content)}
              </div>
              
              {/* hidden file input */}
              <input 
                type="file" 
                accept=".txt" 
                id={`file${doc.id}-upload`} 
                style={{display: 'none'}} 
                onChange={e => handleFileChange(e, doc.id)} 
              />
              
              <button 
                className="search-btn" 
                onClick={() => handleSearch(doc.id)} 
                disabled={!selectedTexts[doc.id] || !selectedTexts[doc.id]?.text || documents.filter(d => d.id !== doc.id && d.content).length === 0}
              >
                Search from Source {doc.id}
              </button>
              

            </div>
          ))}
          
              {/* add document button: show when there is an empty document or the limit is not reached */}
              {(documents.some(doc => !doc.content) || documentCount < 5) && (
                <div className="add-document-btn-container">
                  <button 
                    className="add-document-btn" 
                    onClick={addDocument}
                    title={documents.some(doc => !doc.content) ? "Upload file to empty document" : "Add new document"}
                  >
                    <div className="add-btn-icon">+</div>
                    <div className="add-btn-hint">
                      {5 - documentCount > 0 ? `Add ${5 - documentCount} more` : "Upload files"}
                    </div>
                  </button>
                </div>
              )}
              
              {/* hint when the limit is reached */}
              {documentCount >= 5 && !documents.some(doc => !doc.content) && (
                <div className="max-documents-hint">
                  <div className="max-hint-text">Maximum 5 documents reached</div>
                </div>
              )}
          </div>
        </div>

          {/* drag to adjust the separator */}
        <div 
          className="resize-handle"
          onMouseDown={handleMouseDown}
        ></div>

        {/* document search results overview - display the top1 result of each document */}
        <div className="search-results-overview" style={{ height: `${overviewHeight}px` }}>
          <div className="overview-header">Top Results by Document</div>
          <div className="overview-content">
            {/* show query card when manual searching */}
            {!currentSearchSourceDoc && currentSearchQuery && (
              <div className="overview-result-card query-card">
                <div className="overview-card-header">
                  <span className="overview-doc-name">
                    Your Query
                  </span>
                </div>
                <div className="overview-card-content">
                  <div className="overview-query-text">
                    {currentSearchQuery}
                  </div>
                </div>
              </div>
            )}
            
            {documents.filter(doc => doc.content).map((doc) => {
              // find the best search result of this document
              const docResults = searchResults.filter(result => result.docId === doc.id);
              const topResult = docResults.length > 0 ? docResults[0] : null;
              
              // determine the result to display
              let displayResult = topResult;
              
              // display the last selected result of this document first
              if (lastSelectedResults[doc.id]) {
                // ensure the last selected result is still in the current search results
                const lastSelected = searchResults.find(r => 
                  r.text === lastSelectedResults[doc.id].text && r.docId === doc.id
                );
                if (lastSelected) {
                  displayResult = lastSelected;
                }
              }
              
              // if the current highlight belongs to this document, display the highlighted result first
              if (highlight && highlight.docId === doc.id) {
                const highlightedResult = searchResults.find(r => r.text === highlight.text && r.docId === doc.id);
                if (highlightedResult) {
                  displayResult = highlightedResult;
                }
              }
              
              // check if it is a source document (only display the query when searching)
              const isSourceDoc = currentSearchSourceDoc === doc.id;
              const hasNoResults = !displayResult;
              const shouldShowSelectedText = isSourceDoc && hasNoResults && currentSearchQuery;
              
              return (
                <div 
                  key={doc.id} 
                  className={`overview-result-card doc-${doc.id}-bg${filteredDocId === doc.id ? ' card-selected' : ''}${shouldShowSelectedText ? ' source-doc-card' : ''}`}
                  onClick={() => !shouldShowSelectedText && handleCardClick(doc.id)}
                  style={{ cursor: shouldShowSelectedText ? 'default' : 'pointer' }}
                >
                  <div className="overview-card-header">
                    <span className="overview-doc-name">
                      {doc.file?.name || `Document ${doc.id}`}
                      {filteredDocId === doc.id && <span className="filter-indicator"> (Filtered)</span>}
                      {shouldShowSelectedText && <span className="source-indicator"> (Your Query)</span>}
                    </span>
                    {displayResult && (
                      <span className={`overview-score ${getScoreColorClass(displayResult.score)}`}>Score: {displayResult.score.toFixed(2)}</span>
                    )}
                  </div>
                  <div className="overview-card-content">
                    {displayResult ? (
                      <div className="overview-result-text">
                        {displayResult.text}
                      </div>
                    ) : shouldShowSelectedText ? (
                      <div className="overview-selected-text">
                        {currentSearchQuery}
                      </div>
                    ) : (
                      <div className="overview-no-result">
                        No search results for this document
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>


        {/* reupload confirmation popup */}
        {reuploadConfirm.show && (
          <div className="modal-overlay" onClick={cancelReupload}>
            <div className="modal-content" onClick={(e) => e.stopPropagation()}>
              <div className="modal-header">
                <h3>Confirm Reupload</h3>
              </div>
              <div className="modal-body">
                <p>Are you sure you want to reupload <strong>"{reuploadConfirm.fileName}"</strong>?</p>
                <p className="warning-text">This will clear all current content and cannot be undone.</p>
              </div>
              <div className="modal-footer">
                <button className="modal-btn cancel-btn" onClick={cancelReupload}>
                  Cancel
                </button>
                <button className="modal-btn confirm-btn" onClick={confirmReupload}>
                  Confirm
                </button>
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}

export default App;