"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# DEBUG defaults off; enable locally with DEBUG=True in the environment / .env
DEBUG = os.environ.get("DEBUG", "False").lower() in ("1", "true", "yes")

# Tests run with DEBUG forced off; don't require production secrets for them.
_RUNNING_TESTS = "test" in sys.argv

# SECURITY WARNING: keep the secret key used in production secret
_DEV_SECRET = "django-insecure-dev-only-change-me"
SECRET_KEY = os.environ.get("SECRET_KEY", _DEV_SECRET)
if not DEBUG and not _RUNNING_TESTS and SECRET_KEY == _DEV_SECRET:
    raise RuntimeError("SECRET_KEY environment variable is required in production")

# Comma-separated, e.g. ALLOWED_HOSTS=1.2.3.4,example.com
ALLOWED_HOSTS = [h for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    "apps.tei",
    "apps.search",
    "drf_spectacular",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_PASSWORD = os.environ.get("DB_PASSWORD", "")
if not DEBUG and not _RUNNING_TESTS and not DB_PASSWORD:
    raise RuntimeError("DB_PASSWORD environment variable is required in production")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "uceltic"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": DB_PASSWORD,
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"   # collectstatic target; served by WhiteNoise

# Uploaded TEI files (admin upload) — persisted via a Docker volume.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Same-origin behind the reverse proxy in prod; CORS only needed for local dev.
CORS_ALLOW_ALL_ORIGINS = DEBUG


REST_FRAMEWORK = {
      "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
      # Public, anonymous API (auth is added at the proxy layer in #9).
      # Drop SessionAuthentication so a logged-in admin's cookie doesn't trigger
      # CSRF enforcement on the SPA's POST /api/search/ requests.
      "DEFAULT_AUTHENTICATION_CLASSES": [],
      "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
  }

SPECTACULAR_SETTINGS = {
      "TITLE": "uCeltic API",
      "DESCRIPTION": "Search and TEI document API for the uCeltic manuscript viewer.",
      "VERSION": "1.0.0",
      "SERVE_INCLUDE_SCHEMA": False,
      }