"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import warnings
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# DEBUG defaults off; enable locally with DEBUG=True in the environment / .env
DEBUG = os.environ.get("DEBUG", "False").lower() in ("1", "true", "yes")

# Tests run with DEBUG forced off; don't require production secrets for them.
_RUNNING_TESTS = "test" in sys.argv

# SECURITY WARNING: keep the secret key used in production secret
_DEV_SECRET = "django-insecure-dev-only-change-me"
SECRET_KEY = os.environ.get("SECRET_KEY", _DEV_SECRET)
if not DEBUG and not _RUNNING_TESTS and SECRET_KEY == _DEV_SECRET:
    raise RuntimeError("SECRET_KEY environment variable is required in production")

# Comma-separated, e.g. ALLOWED_HOSTS=1.2.3.4,example.com
ALLOWED_HOSTS = [h for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h]

# Comma-separated full origins (scheme included), e.g.
# CSRF_TRUSTED_ORIGINS=https://1.2.3.4.sslip.io (#63)
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o
]

# Behind Caddy's HTTPS reverse proxy in production: Caddy terminates TLS and forwards
# over plain HTTP with `X-Forwarded-Proto: https`. Trust that header so request.is_secure()
# is correct — otherwise the /admin login POST fails Django's CSRF origin check (the browser
# sends an https:// Origin while Django would otherwise compute http://). Harmless in dev/tests,
# which never send the header.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.headless",
    "apps.accounts",
    "apps.tei",
    "apps.search",
    "apps.analytics",
    "drf_spectacular",
]

# django.contrib.sites is deliberately NOT installed: allauth treats it as optional and
# then derives the host in its emails from the request, which is what we want — the
# deployment's address (<ip>.sslip.io) changes with the box, and a Site row would have
# to be kept in sync by hand.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_PASSWORD = os.environ.get("DB_PASSWORD", "")
if not DEBUG and not _RUNNING_TESTS and not DB_PASSWORD:
    raise RuntimeError("DB_PASSWORD environment variable is required in production")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "uceltic"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": DB_PASSWORD,
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

# allauth rate-limits (e.g. confirm_email) through Django's cache framework.
# LocMemCache is per-process, so under gunicorn's multiple workers each one keeps its own
# counter and the throttle isn't actually enforced. DatabaseCache shares state across
# workers via the existing Postgres — see ADR-0009. The table is created by a migration
# (apps/accounts), so `entrypoint.sh`'s existing `migrate --noinput` creates it in
# production without a separate `createcachetable` deploy step.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Accounts — django-allauth in headless mode (ADR-0004, #64)
# Optional accounts on a public tool: anonymous visitors keep the full workspace;
# signing in adds profile, attribution, and the questionnaire.

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",   # /admin's staff login
    "allauth.account.auth_backends.AuthenticationBackend",   # email + password
]

# Email + password only; no username is ever collected. Django's stock User model
# still has a (unique, required) username column, so allauth derives one from the
# email address on signup — it is an implementation detail no user ever sees.
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*"]
ACCOUNT_UNIQUE_EMAIL = True

# Mandatory activation before the first login: otherwise anyone could register an
# address that isn't theirs. A blocked login re-sends the link (allauth's own flow).
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[uCeltic] "

# Headless only: allauth serves JSON at /api/auth/browser/v1/* and renders no pages,
# so every link it emails must point into the SPA's own routes.
HEADLESS_ONLY = True
HEADLESS_CLIENTS = ("browser",)

# Where the SPA lives, as seen from a mail client: https://<ip>.sslip.io in prod (#63).
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:5173")

HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"{FRONTEND_BASE_URL}/account/verify-email/{{key}}",
    "account_reset_password": f"{FRONTEND_BASE_URL}/account/password/reset",
    "account_reset_password_from_key": (
        f"{FRONTEND_BASE_URL}/account/password/reset/key/{{key}}"
    ),
    "account_signup": f"{FRONTEND_BASE_URL}/account/signup",
}

# Session cookie is the auth mechanism (SPA and API share one origin behind Caddy).
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG and not _RUNNING_TESTS
CSRF_COOKIE_SECURE = not DEBUG and not _RUNNING_TESTS
CSRF_COOKIE_HTTPONLY = False   # the SPA reads it to send X-CSRFToken


# Email
# Dev prints activation links to the console; prod sends them over SMTP. EMAIL_HOST is
# what flips the switch. Missing it in production is NOT fatal — the corpus, search and
# anonymous logging must not go down over unconfigured mail — but registration is dead
# in the water, since nobody can activate an account. So say so, loudly, at boot.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    if not DEBUG and not _RUNNING_TESTS:
        warnings.warn(
            "EMAIL_HOST is not set: activation mail will be written to the container "
            "log instead of being delivered, so no one can activate an account. "
            "Set the EMAIL_* variables (see docs/cd-runbook.md).",
            stacklevel=2,
        )

EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", "uCeltic <no-reply@localhost>"
)


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"   # collectstatic target; served by WhiteNoise

# Uploaded TEI files (admin upload) — persisted via a Docker volume.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Same-origin behind the reverse proxy in prod; CORS only needed for local dev.
CORS_ALLOW_ALL_ORIGINS = DEBUG


REST_FRAMEWORK = {
      "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
      # Public tool with optional accounts (ADR-0004, #64). SessionAuthentication is
      # back — reversing the empty-authenticators setting that the old shared Basic Auth
      # gate made possible — so signed-in visitors are recognised on API calls and their
      # events can be attributed. It enforces CSRF, but only for requests that carry a
      # session: anonymous POST /api/search/ and /api/events/ still need no token.
      # Permission stays AllowAny; only account/profile endpoints require signing in.
      "DEFAULT_AUTHENTICATION_CLASSES": [
          "rest_framework.authentication.SessionAuthentication",
      ],
      "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
      # Wraps DRF's default handler to record every unhandled 5xx as an ErrorReport
      # (#135, ADR-0013). Behaviour of the responses themselves is unchanged.
      "EXCEPTION_HANDLER": "apps.analytics.error_capture.exception_handler",
  }

SPECTACULAR_SETTINGS = {
      "TITLE": "uCeltic API",
      "DESCRIPTION": "Search and TEI document API for the uCeltic manuscript viewer.",
      "VERSION": "1.0.0",
      "SERVE_INCLUDE_SCHEMA": False,
      }