# Generated by Django 6.0.4 on 2026-09-02 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('query_origin', models.CharField(choices=[('typed', 'typed'), ('selection', 'selection')], max_length=16)),
                ('window_size_ratio', models.FloatField()),
                ('step_size', models.PositiveIntegerField()),
                ('dissimilarity_threshold', models.FloatField()),
                ('top_k', models.PositiveIntegerField()),
                ('versions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'search history entries',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
