# Generated by Django 6.0.4 on 2026-05-08 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teidocument',
            name='xml_file',
            field=models.FileField(upload_to='tei/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'tei'])]),
        ),
    ]
