# Generated by Django 6.0.4 on 2026-05-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tei', '0002_alter_teidocument_xml_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='teidocument',
            name='anchors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teidocument',
            name='plain_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
