# Generated by Django 6.0.4 on 2026-05-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tei', '0003_teidocument_anchors_teidocument_plain_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teidocument',
            name='plain_text',
        ),
        migrations.AddField(
            model_name='teidocument',
            name='word_array',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
