# Generated by Django 6.0.4 on 2026-08-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tei', '0006_acallam_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('person', 'Person'), ('place', 'Place')], max_length=16)),
                ('headword', models.CharField(max_length=255)),
                ('headword_source', models.CharField(choices=[('derived', 'Derived from the corpus'), ('manual', 'Set by hand')], default='derived', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'name entities',
                'ordering': ['headword'],
            },
        ),
        migrations.AddField(
            model_name='teidocument',
            name='name_index',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
